### ISSUE TITLE
Unable to use GLM 0.9.6 with Android NDK

### ISSUE THREAD

**Issue by Donorhan** [g-truc/glm#284]
I'm updating GLM from 0.9.5.4 to 0.9.6.0 and something is wrong during the Android NDK compilation: I've got errors with std functions not founds:

> glm/gtc/../detail/func_common.inl:229:16: error: 'std::trunc' has not been declared  using ::std::trunc;

Same error with "std::round", "std::asinh", "std::atanh", "std::acosh", …. Everything was working well before the last update. (I'm using gcc 4.9 and compile with --std=c++11)

Thanks!

**Comment by DonoSybrix** [comment]
Sorry to say that, but the problem is back with the last version (GLM 0.9.6.2) :/

**Comment by Groovounet** [comment]
Ahhh, I think I understand the issue...

#if GLM_PLATFORM != GLM_PLATFORM_ANDROID
#	define GLM_HAS_CXX11_STL 0
#elif GLM_COMPILER & (GLM_COMPILER_LLVM | GLM_COMPILER_APPLE_CLANG)
#	define GLM_HAS_CXX11_STL __has_include(<__config>)
#else
#	define GLM_HAS_CXX11_STL ((GLM_LANG & GLM_LANG_CXX0X_FLAG) && \
		((GLM_COMPILER & GLM_COMPILER_GCC) && (GLM_COMPILER >= GLM_COMPILER_GCC48)) || \
		((GLM_COMPILER & GLM_COMPILER_VC) && (GLM_COMPILER >= GLM_COMPILER_VC2013)))
#endif

Damn!
Fixed with #if GLM_PLATFORM == GLM_PLATFORM_ANDROID

**Comment by DonoSybrix** [comment]
Indeed! Everything is ok now :D.

Thanks!

**Comment by richardeakin** [comment]
FWIW, I found a stackoverflow post that sheds some light on the android / C++11 STL math library problem:

http://stackoverflow.com/questions/22922961/c11-cmath-functions-not-in-std-namespace-for-android-ndk-w-gcc-4-8-or-clang-3

**Comment by jandoerntlein** [comment]
Problem reoccurs in 0.9.7.3. There is no "GLM_PLATFORM_ANDROID" check in the file "setup.hpp" anymore. Was the patch intentionally removed from later versions?
