### ISSUE TITLE
glm::mod() behaves differently for int and float with negative values

### ISSUE THREAD

**Issue by sponji** [g-truc/glm#308]
Seems like `glm::mod<int>()` gives wrong results for negative values. For example, `glm::mod<int>(-1, 10)` gives -1, but `glm::mod<float>(-1.0f, 10.0f)` gives 9.0f.

**Comment by Groovounet** [comment]
Hi,

The source of the issue is the rounding of 'mod' with GLSL which can't be translated into integers.

As a return, I removed the integer overload and added a fmod overload in glm/gtx_common.hpp which rounding supports float and int flavors.

This version is based on HLSL version of fmod. http://stackoverflow.com/questions/7610631/glsl-mod-vs-hlsl-fmod

This work has been done on master branch for GLM 0.9.7 release.

Thanks,
Christophe
