### ISSUE TITLE
Incorrect default constructed quaternion

### ISSUE THREAD

**Issue by tlescoat** [g-truc/glm#417]
For the quaternion defined in glm/gtc/quaternion.hpp:

If `GLM_FORCE_NO_CTOR_INIT` is defined, then the default constructor will create `(0, 0, 0, 0)`, but without this define the default constructor will create `(0, 0, 0, 1)`, which is the more convenient behavior. So, when switching whether this macro is defined, some code can break.

Either always provide a default constructor for `tquat` or make the default constructor create `(0, 0, 0, 0)`. I can do a pull request if needed, but I need a decision on this question.

**Comment by Groovounet** [comment]
Erm, it's basically the purpose of GLM_FORCE_NO_CTOR_INIT: not doing constructor initialization so that it requires you to do it.

Others types like matrices will also construct unusable instances until properly initialized.

If you need to not initialize vectors, matrices or quaternions only sometimes, an alternative is to use glm::uninitialize, eg:

```
glm::vec4 v(glm::uninitialize); // Uninitialized vec4, internal GLM code use it then useful for optimization purposes
```

If you generally need GLM to not initialize then you can use GLM_FORCE_NO_CTOR_INIT and initialize explicitly when needed.

```
#define GLM_FORCE_NO_CTOR_INIT 
#include <glm/glm.hpp>

glm::mat4 m; // as good as garbage
...
m = glm::mat4(1.0f); // initialize m with an identity matrix using the equal operator. 
```

Thanks,
Christophe

**Comment by tlescoat** [comment]
Thanks for the fast answer !
Fair point - when I looked at it, I didn't thought it was for uninitialized data (because it isn't for vectors for example) but for POD : with that define, `tvec` classes are POD whereas they only are standard layout without.

IMHO:
 - `tvec` classes should always use `= default` constructors (pod, less code to maintain, etc...)
 -  other classes (`tmat`, `tquat`) should still have the same mechanism as current
 -  the macro `GLM_FORCE_NO_CTOR_INIT` should be renamed to be more explicit, for example `GLM_FORCE_UNINITIALIZED_DEFAULT`, I think it is less ambiguous (still IMHO)
