### ISSUE TITLE
Lack of Search in Documentation

### ISSUE THREAD

**Issue by Cidubic** [g-truc/glm#574]
Two things to talk about, the first being that I would appreciate if the glm main page and documentation were linked together, so for instance, if you are at: https://glm.g-truc.net/0.9.4/api/modules.html then clicking the glm icon should send you back to: https://glm.g-truc.net/

The second and more important is the lack of a search functionality within the online documentation, which is a disappointment, as that makes finding something specific in the documentation much slower, unless you already know exactly where to go... which isn't useful for the majority of people, as the reason people are looking in the documentation is usually because they don't know something, so being forced to know which module contains a particular piece is bothersome.

Another confusing part of the documentation is the decision to place all of the "core" library at the bottom of the page, meaning for the (ideally) most common things someone might look for they have to search through the extensions first; which isn't particularly intuitive.

Also, a bunch of the types have constructors, but I seriously cannot find any of the documentation regarding constructors, which is odd, since you would likely want to be able to assure yourself of how the constructors work.

**Comment by Groovounet** [comment]
4/ Most users of GLM know GLSL so most actually already know how to use core functionalities which may explain why the documentation is more lightweight here. Beside few caveats, it's basically the same as GLSL, including constructors. It's probably possible to improve the doxygen documentation for better coverage and PRs are always welcome for that. :D

3/ The API documentation is generated with Doxygen which basically explains point 3. It's not a decision, it was generated this way. Is it possible to change it? Maybe, not sure, don't know. You can always try to make a PR. :D 

2/ Regarding the first point, well, again it's generated. Not sure, there is an option to do what you want. On the frontpage, there is a link to the website.

1/ At least one good news: For the next version of GLM (0.9.9) which is still under development and not released, **there is a search bar**. I uploaded it [here](http://glm.g-truc.net/0.9.9/api/index.html) for you so that you can have a look. Enjoy!

Thanks,
Christophe
