### ISSUE TITLE
intersectRayTriangle returns barycentric Z 4.5

### ISSUE THREAD

**Issue by joobei** [g-truc/glm#6]
when fed with 
ray origin glm::vec3(0,0,0);
ray direction glm::vec3(0,0,-1);

and 3 vertices (already transformed to world coordinates):
v0 = glm::vec3(0.5,0.5,-4.5);
v1 = glm::vec3(-0.5,-0.5,-4.5);
v2 = glm::vec3(0.5,-0.5,-4.5);

It returns barycentric coordinates a = 0, b = 0.5 , c = 4.5
If I understand correctly, a+b+c should equal to 1.

They don't seem to be barycentric coordinates, they seem like.. normal cartesian coordinates of the intersection point.

**Comment by JesseTG** [comment]
Can this be considered closed?

**Comment by evg-zhabotinsky** [comment]
Barycentric coordinates are still not explained in docs.
Should I check that my observations still hold (except for backface culling, #194) and post a 1-line pull request?

**Comment by Groovounet** [comment]
If somebody is interested to improve / fix this code, I think a pull request is the best approach. :)

**Comment by Groovounet** [comment]
This issue should be fixed in master branch for GLM 0.9.9 release.

Thanks for reporting,
Christophe

**Comment by Squareys** [comment]
It looks like now the barycentric z coordinate is never assigned, instead the value passed for it is merely divided by a determinant? (https://github.com/g-truc/glm/blob/master/glm/gtx/intersect.inl#L89)

Also, the test case doesn't actually use the z coordinate for the triangle vertices which makes it impossible to catch this "bug" (?) with it: https://github.com/g-truc/glm/blob/master/test/gtx/gtx_intersect.cpp#L12

I guess you can always calculate it from the other two coordinates, in which case a little documentation about that would be very appreciated.

Or am I missing something?

Kind regards, Jonathan.

**Comment by edap** [comment]
thank you @nlguillemot for your explanation

**Comment by jpanneton** [comment]
@nlguillemot Note that when calling glm::intersectRayTriangle(orig, dir, v0, v1, v2, baryPosition),
`intersection = orig + baryPosition.z * dir`
should in theory be equal to
`intersection = v0 + (baryPosition.x * (v1 - v0) + baryPosition.y * (v2 - v0))`
However, in practice, the latter is more accurate than the former.
In fact, I was playing with a 3D Gaussian function the other day and as we all know, this function usually converge to 0 pretty quickly. So, I tried to draw a contour line around it at mouse position using glm::intersectRayTriangle and it turned out that using the latter allowed me to draw the contour line further and more accurately than the former (using the resulting y-coordinate of the intersection to generate it).
So, if floating-point precision is an issue, use the latter.
Otherwise, use the former (faster to compute).
