### ISSUE TITLE
glm::cross should support 2d vector.

### ISSUE THREAD

**Issue by zhou13** [g-truc/glm#621]
So I don't need write my own:
````
double cross(dvec2 const& a, dvec2 const& b)
{
    return a.x * b.y - b.x * a.y;
}
````

**Comment by bcrist** [comment]
What does that function have to do with the cross product?  That looks suspiciously like `glm::determinant` to me.

**Comment by zhou13** [comment]
This is often used in computation geometry.  You can understand it as the the length of vector `a x b` if we treat a and b as a 3d vector in `z=0` plane..

**Comment by bcrist** [comment]
Sure, `length(cross(dvec3(a,0), dvec3(b,0)))` and `determinant(dmat2(a,b))` are equivalent, and both represent the area of a 2D parallelogram with sides `a` and `b`, which is a useful thing.  But that doesn't mean it should be called the cross product.

**Comment by zhou13** [comment]
Well, naming is just a convention.  For example, numpy support call such 2d operator in cross product: https://docs.scipy.org/doc/numpy/reference/generated/numpy.cross.html, which may be not very precise. I could write `return glm::determinant(glm::dmat2(a, b))`, but that is a little bit awkward.

**Comment by bcrist** [comment]
I think this is a good addition to GLM, but I still think it shouldn't be called `glm::cross`, or at least should be put in an extension header so that people who don't want this overload don't get it.  For one thing, GLSL, HLSL, and Cg all define the `cross` function specifically as a function that both returns and takes 3-component vectors as parameters.  Mathematically speaking, the cross product, scalar triple product, and the function described here are all just types of [exterior products](https://en.wikipedia.org/wiki/Exterior_algebra#Cross_and_triple_products).  Perhaps a new `GTX_exterior_product` extension would be useful?

**Comment by Groovounet** [comment]
I added a vec2 implementation of cross in within an GTX_exterior_product extension. :D

Thanks for suggesting and discussing the topic!
Christophe
