### ISSUE TITLE
Swizzles in functions need manual type conversion.

### ISSUE THREAD

**Issue by visorz** [g-truc/glm#626]
Thank you for your powerful GLM library, that I am using since 4 years now. 

Unfortunately swizzles need a workaround when used in GLM functions. I would like to request that both of the following code lines work in a future release.

```glsl
// using glm 0.9.8.4
vec3 a, b;
vec2 yes = glm::max( a.xy(), vec2( b.yz ) );  // ok using workaround
vec2 no  = glm::max( a.xy, b.xy );            // compile error
```
Error message is:
`glm\detail\func_common.inl(25): error C2338: 'max' only accept floating-point or integer inputs`

Tested with the following GLM settings:
- GLM: Windows platform detected
- GLM: version 0.9.8.4
- GLM: Visual C++ compiler detected
- GLM: 64 bits model
- GLM: SSE4.2 instruction set
- GLM: C++0x
- GLM: Language extensions enabled
- GLM: Swizzling operators enabled
- GLM: Core library included

It looks to me as if there is functionality missing in `glm::max( )` to recognize `a.xy` as of type `vec2`.

**Comment by Groovounet** [comment]
This behaviour is actually described in the manual and there is unfortunately no real workaround it to date.

swizzle operators don't return vec types but a magic swizzle type that can be implicitly converted.

Due to 'max' overloading, the compiler can't figure out the right conversion...

Thanks,
Christophe
