### ISSUE TITLE
glm::vec4 constructor not constexpr

### ISSUE THREAD

**Issue by haikarainen** [g-truc/glm#653]
`GLM_CONSTEXPR_SIMD` under architecture SSE2 makes `glm::vec4` constructor not be a `constexpr`. Pretty obvious but doesn't happen for `glm::vec3` or `glm::vec2`.

Please see https://github.com/g-truc/glm/issues/556

Using Arch Linux GLM package glm 0.9.8.4-2

Testing with C++14/C++17

**Comment by Groovounet** [comment]
Oh well, I thought I could fix this issue but it only cause a lot of problems and I resolved by adding an item in the manual FAQ.

There is an incompatibility between SIMD intrinsics and constexpr. It could work with packed types because they don't use SIMD instructions however the use of constexpr in vector types is handled using defines, I would need to find a template approach or something to make it work.

Thanks for reporting,
Christophe
