### ISSUE TITLE
glm/gtx/simd_vec4.hpp has been moved or is inexistant is latest releases

### ISSUE THREAD

**Issue by frtru** [g-truc/glm#688]
I was using an older version of glm which included simd_vec4.hpp in glm/gtx (just checked with 0.8.4 and it's there). Now I can only see this file in your simd branch. In fact, from 0.9, I can't find the said file. Is there any reason why it is not packaged anymore in the releases?

**Comment by Groovounet** [comment]
simd_vec4.hpp was removed. 

When using glm/gtx/type_aligned.hpp instead, especially glm::aligned_vec4 will be a great raplacement as it generates SIMD code too.

In fact, glm::aligned_vec4 is just a glm::vec4 specialized for SIMD code generation so that it interacts smoothly between glm::aligned_vec4 and glm::vec4
