### ISSUE TITLE
constexpr all the (non-SIMD) functions

### ISSUE THREAD

**Issue by KageKirin** [g-truc/glm#713]
Hello,

I've been using glm for ~8 years now (mostly in personal projects, but ~4 years in professional projects as well). Great work on this lib!

So, by looking closer at the vector and matrix functions, I noticed that technically, the ones that do not rely on SIMD operations could all be flagged to be constexpr, which would allow to perform a number of computations at compile time.

Whether or not this is a good idea is to debate.
What do you think? Would this be worth to add?

Regards.

**Comment by htmlboss** [comment]
Been using this library also since forever, and imo it would be a nice feature for those who have supporting compilers. I wouldn't mind lending a hand with this idea!

**Comment by KageKirin** [comment]
C++14 is the requirement for this to work, so prefixing the function definitions with `GLM_CONSTEXPR_CXX14` from PR #712 should do the magic.

Then again, I'm not sure if this introduces issues in other codebases relying on the operations being executed at run-time, rather than compile-time. Any ideas?

Cheers.

**Comment by htmlboss** [comment]
I don't think it would introduce any compat issues since the macro would deal with `constexpr` support. Here are the attributes for a function to be valid `constexpr`: https://www.ibm.com/support/knowledgecenter/en/SSGH3R_13.1.0/com.ibm.xlcpp131.aix.doc/language_ref/constexpr_functions.html

So there is obviously some forethought required by the person actually calling the function to ensure it CAN be evaluated as `constexpr`. Here's the way I see it: it's a hint for the compiler to see if it can be evaluated, if yes, yay we save some runtime calculations. If not, no difference to the end-user.

**Comment by KageKirin** [comment]
True. But then again, constexpr functions are inline by default. Changing all functions to constexpr _might_ blow up the compiled code size (I haven't benchmarked this, though).

**Comment by nephatrine** [comment]
I'd at least love to see the const operator[]s be constexpr. Those are usually fairly simplistic functions and good candidates for inlining regardless.

**Comment by Groovounet** [comment]
Hi,
So you can notice that master branch has a lot of improvements to better support constexpr. GLM implementation now requires C++ 14 constexpr support as otherwise there isn't much we can do with it and it complexify both the code and testing to implement both.
- All vec1..4 types supports constexpr on both constructors and operators. 
- matMxN types supports constexpr on constructors and vector relation operators. More will be added to have full coverage.

A caveat is that constexpr is not compatible with anonynous struct, meaning that SIMD optimization must be disable with GLM_FORCE_PURE or using the compiler build arguments.

Ideas for a better handling of this limitation would be welcome. Pushing compiler vendors to support constexpr on their instructinc functions would be great too. :)

Thanks for contributing,
Christophe

**Comment by mikezackles** [comment]
I just thought I'd point out that this also applies to the trivially constant functions like `glm::pi<double>` etc. Perhaps there could be two macros, one for SIMD stuff and one for everything else?

**Comment by Trass3r** [comment]
>     matMxN types supports constexpr on constructors and vector relation operators. More will be added to have full coverage.

What's the status of this? I don't see any constexpr matrix operators or operations like rotate.
