### ISSUE TITLE
feature request: frustum plane extraction from view projection matrix

### ISSUE THREAD

**Issue by volcoma** [g-truc/glm#716]
Would love some functions for frustum plane extraction from view projection matrix with respect to LH/RH ZO/NO. Thank you.

**Comment by catdsnny** [comment]
upvote - many people writing this over and over - needed for view culling

**Comment by htmlboss** [comment]
I'm assuming this is the paper you are referring to? [http://gamedevs.org/uploads/fast-extraction-viewing-frustum-planes-from-world-view-projection-matrix.pdf](http://gamedevs.org/uploads/fast-extraction-viewing-frustum-planes-from-world-view-projection-matrix.pdf)

How would you like the extracted planes to be returned? In my engine, I fill an `std::array<glm::vec4, 6>` with the planes. And use an enum defined as `TOP, BOTTOM, LEFT, RIGHT, NEAR, FAR` to access the corresponding plane. 

@Groovounet Would something like the following fit in the glm code style?

```c++
namespace glm {

enum class FrustumPlane {
TOP,
BOTTOM,
LEFT,
RIGHT,
NEAR,
FAR
}

// Clip matrix would be constructed here, and each plane equation would be extracted, normalized, and placed into returned array.
std::array<glm::vec4, 6> extractViewFrustum(const glm::mat4x4& projMat, const glm::mat4x4& viewMat);

} // namespace glm
```

I have the working code in my engine, but I would need some guidance to integrate it with glm 😝

**Comment by catdsnny** [comment]
Yes thats the code fragment.  I actually based on my final code some other
Direct X examples and just flipped the col/row matrix.  I think the
top/bottom/near/far/left/right works well for most people.  Could return as
an array or as a new glm::frustum object so that people could add on
bounding detection.  Really depends on how far glm becomes more of an
engine.  I see engine-ish features emerging in the later releases, like ray
intersect plane and so on.  Adding frustum extraction and bounds testing
seems to be a natural extension of where this thing is headed but it's your
baby :)

**Comment by Groovounet** [comment]
I didn't really investigate this issue yet but the feature seems interesting. For a PR, 
- It would need to be relatively generic code so that is works for dmat4 too, for example.
- It would need tests.
- Class enum  and std::array are not the favourite tools for compatibility with C++98. It's possible to use C++ 11 features but typically, there are fallback to C++ 98.

Thanks,
Christophe
