### ISSUE TITLE
vec4 constructor is not constexpr

### ISSUE THREAD

**Issue by therocode** [g-truc/glm#783]
out of these 4, all work except the vec4 one, which complains:
error: call to non-constexpr function 'glm::vec<4, T, Q>::vec(T, T, T, T) [with T = float; glm::qualifier Q = (glm::qualifier)0]

static_assert(glm::vec1(1.0f).x > 0.0f);
static_assert(glm::vec2(1.0f, 1.0f).x > 0.0f);
static_assert(glm::vec3(1.0f, 1.0f, 1.0f).x > 0.0f);
static_assert(glm::vec4(1.0f, 1.0f, 1.0f, 1.0f).x > 0.0f);

https://godbolt.org/g/AGD3k1

**Comment by Groovounet** [comment]
This issue should be fixed in master branch and GLM 0.9.9.1 release.

The behavior is that constexpr will be consistent across all types. If the project has automatic SIMD code generation, GLM will try to produce code with SIMD instructions which is imcompatible with constexpr. As a result you will need to use GLM_FORCE_PURE to disable SIMD instructions.

Thanks,
Christophe
