### ISSUE TITLE
The master branch breaks too often

### ISSUE THREAD

**Issue by hmarthinsen** [g-truc/glm#785]
Lately, the master branch has often failed building, breaking other projects that depend on glm. This is very annoying. Please ensure that new commits don't break the master branch.

**Comment by Groovounet** [comment]
Erm, it's not an easy thing as typically break happens because on the developer machine build and test pass but with others compilers, different configurations

- What's your suggestions for "ensure that new commits don't break the master branch"?
- What's your need for using trunk branch instead of a released version?
- Would a "release" branch solve the issue?

**Comment by hmarthinsen** [comment]
OK, sorry, just venting some steam. I understand that different configurations complicate the matter. In some of the projects I work on, the build system automatically updates glm to the latest commit in the master branch, and sometimes this causes the project build to fail, because of changes in glm. In the projects we want to stay on the latest stable version of glm, so a release branch that points to the latest released version is a great idea!

The project build broke tonight because of glm, but I'll post that in a new issue. It may be an actual bug in glm.

**Comment by Groovounet** [comment]
I created the stable branch based on last release version. I'll keep it updated with last release.
https://github.com/g-truc/glm/tree/stable

Thanks,
Christophe

**Comment by hmarthinsen** [comment]
Thank you! 👍
