### ISSUE TITLE
Add hashing support

### ISSUE THREAD

**Issue by Undeterminant** [g-truc/glm#81]
If implementations of [std::hash](http://en.cppreference.com/w/cpp/utility/hash) are provided for integer vectors/matrices, it'll allow you to use them as keys in the new [std::unordered_set](http://en.cppreference.com/w/cpp/container/unordered_set) and [std::unordered_map](http://en.cppreference.com/w/cpp/container/unordered_map) containers that C++11 provides.

It probably wouldn't make sense to add hashing for float vectors.

**Comment by bcrist** [comment]
@Nemikolh I don't see any advantage to placing hash functions in `glm` instead of `std`.  Specializations of `std::hash` belong in `namespace std`.  If a user wants to use a custom hash function, they can specify it on a container-specific basis as you note, or they can just not include the header for the extension that implements the default hash functions, and put their own implementation in `std` instead.  Most people will probably just want to use the default implementation and there's no sense in punishing them for no reason (forcing them to use another template parameter on the container).

**Comment by Undeterminant** [comment]
Another random clarification is that the regular `map` and `set` in C++ are based off of trees, which is why you need < operators. It doesn't make sense to order vectors and matrices, but it makes sense to compare them for equality, which is why hashing would be useful.

**Comment by plasmacel** [comment]
I have implemented the template specializations of std::hash for glm types.
I'm going to create a pull request soon.

**Comment by Groovounet** [comment]
Nice!! :)

**Comment by JesseTG-HBO** [comment]
Can't this be closed now?

**Comment by plasmacel** [comment]
well, hash function for dual_quat type is still missing. i think i do it tonight.

**Comment by JesseTG-HBO** [comment]
*Now* this can be closed.
