### ISSUE TITLE
Quaternions with w-value greater than 1 result in NaN values

### ISSUE THREAD

**Issue by ifl0w** [g-truc/glm#820]
Currently, I am writing a small game engine and I stumbled over an issue with the quaternions of this library (version 0.9.9.2). 
I only use the constructors and functions/operators of glm to initialize and to manipulate them, but occasionally I am getting quaternions with a w-value greater than 1. This results in nan values for any succeeding `glm::angle(quat)` call since `acos` is only defined for [-1, 1].

Shouldn't there be any assurance that glm::angle never returns nan? Or that a multiplication of quaternions never returns a w-value greater than 1?

After some debugging, I found that the following values produce the error but I do not know if the values of the quaternions x, y and z are not already invalid themselves.

```
quat x = quat();
x.x = -0; x.y = 0; x.z = 0; x.w = 1;

quat y = quat();
y.x = 0; y.y = -0.00174532831; y.z = 0; y.w = 0.99999845;

quat z = quat();
z.x = -0.00436332822; z.y = 0.00436370261; z.z = 1.9035986e-05; z.w = 0.999996066;

auto err = y * z * x;
auto nan = angle(err); // should be NaN
```

For now, I am working around this issue by clamping the w-value but this seems kinda hacky. Is there a better workaround for this?
```transform.rotation.w = glm::clamp<float>(transform.rotation.w, -1, 1);```

**Comment by CaptainCarrot** [comment]
The issue is that one of the quaterions is not of unit length, and therefore the product isn't either. As the product then is no valid rotation anymore, the angle is ill-defined and as such the result is to be expected.

Instead of clamping w you should normalize your quaternions, since a product of unit quaternions is not necessarily unit quaternion because of floating point rounding issues. It is common practice to renormalize quaternions at critical points whenever you rely on it having unit length.

**Comment by ifl0w** [comment]
Thank you for the explanation!
Though wouldn't it be an option to normalize the quaternion internally in the glm::angle(quat) function to prevent any hard to find NaN errors? Or is there a reason for not doing that?

**Comment by UniQP** [comment]
I stumbled about the same issue today.

Either `glm::angle(quat)` should work for non-normalized quaternions or the documentation of `glm::angle(quat)` should state that its argument needs to be normalized.
