### ISSUE TITLE
Basic vector types aren't trivially copyable with GLM_FORCE_CTOR_INIT defined

### ISSUE THREAD

**Issue by ezillinger** [g-truc/glm#943]
I'm unable to put an ivec2 in a union if GLM_FORCE_CTOR_INIT is defined. I'm using the latest GLM 0.9.9.6 master and my compiler is MSVC 15.9.15. It works correctly if GLM_FORCE_CTOR_INIT is not defined.

`function was implicitly deleted because 'InputEvent' has a variant data member 'InputEvent::m_cursor' with a non-trivial copy constructor` 

This worked fine in GLM 9.8.4 when constructor initialization was the default behavior.

**Comment by Groovounet** [comment]
With GLM_FORCE_CTOR_INIT  contructors are explicitly initialized to 0 which is against C++ definition of trivially copyable.

Thanks,
Christophe

**Comment by totalgee** [comment]
This is strange, because in older versions of GLM (which did initialize to 0 by default) `vec3` and other types **did** report being trivially copyable:

```c++
    static_assert(std::is_trivially_copyable<glm::vec3>::value, "vec3 is trivially copyable");
```

(I was using Cinder 0.9.1, which previously used GLM 0.9.7.3, which had the behaviour that this static_assert would not be triggered. Now I've switched to Cinder 0.9.2, which uses GLM **0.9.9.5**, and this assert is triggered -- and that's regardless whether I #define GLM_FORCE_CTOR_INIT or not. This is with VS 2015 and now VS 2019.)

**Comment by totalgee** [comment]
Is there a flag I can set to make the GLM classes trivially copyable, as they were before? I see there is this in the `setup.hpp` file, but it's not used anywhere (except in test code):

```c++
#define GLM_HAS_TRIVIAL_QUERIES 0
```
