### ISSUE TITLE
What's the point of removal of cmake install/uninstall scripts?

### ISSUE THREAD

**Issue by asavah** [g-truc/glm#947]
After https://github.com/g-truc/glm/commit/5f352ecce21bb1ab37fa56fac0f383c779b351a3 make install will obvously fail.
What's the point of this?
Removing .pc file is unfriendly towards linux distros, many packages rely on pkg-config in order to detect presence of glm.
Even if for whatever reason this is necessary manual installation steps should be properly documented.

**Comment by balducci** [comment]
I also stumbled on this
Maybe installers are supposed to use some other means of installation? (I mean not manually)
thanks

**Comment by Groovounet** [comment]
CMake installer and uninstaller scripts are gone for now. Why not adding it back in the future if there is high demand but the PR will require manual change to add documentation about the how to use the installer scripts and their features.

Thanks,
Christophe

**Comment by balducci** [comment]
Out of curiosity: how is one supposed to install glm system wide now?
thanks

**Comment by Crunkle** [comment]
Unless I am misunderstanding something, the rationale of "needs documentation" doesn't give logical sense to be removing the install target entirely. It was clearly used by a fair number of developers who will now have to resort to janky alternatives.

**Comment by shogerr** [comment]
I was just attempting to use the install targets (and uninstall target) on a Windows system. Sure, I seem to be missing something in deploying it properly, which is why I'm in the issues section, but I'd be happy to push an update to the documentation with the steps needed to use the target on Windows.

Or, I guess I'll noodle together some janky alternative.

**Comment by joakim-tjernlund** [comment]
> CMake installer and uninstaller scripts are gone for now. Why not adding it back in the future if there is high demand but the PR will require manual change to add documentation about the how to use the installer scripts and their features.
> 
> Thanks,
> Christophe

Why was it removed ?

**Comment by bdubbs** [comment]
If we are going to install it manually, how do we do that?  I can copy the library to /usr/lib, but what headers need to be copied?  What about docs? cmake files?  .pc file?

**Comment by thokra1** [comment]
I love glm and I thank you for putting in all the hard work, but you might as well remove CMake from the mix entirely if you're not gonna provide proper means for downstream usage without manual tinkering. 

Without install scripts, downstreams are forced to manually copy the necessary stuff around and create their own import targets instead of just taking the installed module.

Yes - I know it's not a lot of effort to do it yourself, but CMake generates everything that's necessary for you! It makes absolutely no sense to remove this and not providing proper exports is the bane of all the shitty old-school CMake projects out there.

**Comment by eli-schwartz** [comment]
> My recommandation here is that people interested in having an installer and uninstaller should work together to design a solution that works for all of you.

Given the previous installer/uninstaller was removed with absolutely no explanation whatsoever, would you mind clarifying, for the record, why you had the slightest belief that that itself wasn't the solution that worked for everyone?

Because I rather suspect that everyone complaining here would agree, the solution is "git revert 5f352ecce21bb1ab37fa56fac0f383c779b351a3".

As far as I can tell, the removal happened purely for the lulz. No commit messages, no rationale, and when this issue was opened to ask "why did nonsensical things happen", you've responded with evasiveness. This is extremely bad for confidence in the software. It seems like you suddenly decided you don't want people to use it, and therefore went out of your way to break it. Please explain.

**Comment by svenstaro** [comment]
Arch Linux glm downstream maintainer here. I suggest reverting https://github.com/g-truc/glm/commit/5f352ecce21bb1ab37fa56fac0f383c779b351a3. It was working perfectly fine and didn't need removal.

**Comment by Polynomial-C** [comment]
There's now [glm-0.9.9.6 breaks "find_package(glm REQUIRED)" in CMake](https://bugs.gentoo.org/695648) (Gentoo downstream bug report).

Thanks for deliberately breaking this software without even giving any rationale...

**Comment by svenstaro** [comment]
> Thanks for deliberately breaking this software without even giving any rationale...

Now I disagree with the author's decision as well but I don't think resorting to snark is the right way to go about this.

**Comment by svenstaro** [comment]
I downstream fixed the package using pre-generated files which you can find [here](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/glm). It's not great and I want the files back in glm but for the time being you can use the ones from Arch.

**Comment by Wedrew** [comment]
Seeing the same thing here... Lost the ability to reference header files glm in my cmake project using FetchContent_Populate. It relied on the install scripts. I'll have to use 0.9.9.5 until this is fixed :(

**Comment by tgurr** [comment]
Exherbo maintainer here, the removed CMake install target worked fine for us as well.

**Comment by Groovounet** [comment]
Any volunteer to add a documentation on what's the features available and how to use it?

**Comment by handsomematt** [comment]
> Any volunteer to add a documentation on what's the features available and how to use it?

Features available for what? It was working the intended CMake way before, the community suggestion for installer/uninstaller is to revert your commit. Pushing such a breaking change for no reason is ridiculous....

**Comment by Groovounet** [comment]
I am resolving this issue by looking for a maintainer for this feature in #961. Feel free to volunteer.

**Comment by Groovounet** [comment]
Any one to review this PR (https://github.com/g-truc/glm/pull/968) to resolve this issue ?

**Comment by Twinklebear** [comment]
@Groovounet would you mind taking a look at #966? I think it's a simpler and easier to maintain solution for a header only library like GLM. I'll also volunteer myself to maintain it, but another benefit is it shouldn't require a lot of maintenance either, and has tests added into CI to verify it's working.
